# Generated by Django 6.0.2 on 2026-02-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150, verbose_name=' ')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
